name: Publish Experimental Release
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  experimental-release:
    name: Experimental Dev Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # For publishing to GitHub releases
      id-token: write # required for OIDC / Trusted Publishers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      # Update npm to support Trusted Publishers
      - name: Update npm
        run: npm install -g npm@11.5.1

      - name: Install Dependencies
        run: npm install

      - name: Prepare Project
        run: npx nuxi prepare

      - name: Build Project
        run: npm run dev:build

      - name: Lint Code
        run: npm run lint

      - name: Prepack
        run: npm run prepack

      - name: Audit Dependencies
        run: npm audit signatures

      - name: Set Experimental Version
        run: npm version --no-git-tag-version 0.0.0-experimental-${GITHUB_SHA::7}

      - name: Publish Experimental Release
        run: npm publish --access public --tag experimental
